import Footer from "./components/Navbar/Footer";
import Navbar from "./components/Navbar/Navbar";
import "./globals.css";
import { Inter, Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Teacher's Corner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
        style={{ backgroundColor: "#112", color: "#eff" }}
      >
        <div className="container">
          <Navbar></Navbar>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
